// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: imposter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImposterServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ImposterServerMessage_RoleAssignment
	//	*ImposterServerMessage_RevealProgress
	Body          isImposterServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImposterServerMessage) Reset() {
	*x = ImposterServerMessage{}
	mi := &file_imposter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImposterServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImposterServerMessage) ProtoMessage() {}

func (x *ImposterServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_imposter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImposterServerMessage.ProtoReflect.Descriptor instead.
func (*ImposterServerMessage) Descriptor() ([]byte, []int) {
	return file_imposter_proto_rawDescGZIP(), []int{0}
}

func (x *ImposterServerMessage) GetBody() isImposterServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ImposterServerMessage) GetRoleAssignment() *RoleAssignment {
	if x != nil {
		if x, ok := x.Body.(*ImposterServerMessage_RoleAssignment); ok {
			return x.RoleAssignment
		}
	}
	return nil
}

func (x *ImposterServerMessage) GetRevealProgress() *RevealProgress {
	if x != nil {
		if x, ok := x.Body.(*ImposterServerMessage_RevealProgress); ok {
			return x.RevealProgress
		}
	}
	return nil
}

type isImposterServerMessage_Body interface {
	isImposterServerMessage_Body()
}

type ImposterServerMessage_RoleAssignment struct {
	RoleAssignment *RoleAssignment `protobuf:"bytes,1,opt,name=role_assignment,json=roleAssignment,proto3,oneof"`
}

type ImposterServerMessage_RevealProgress struct {
	RevealProgress *RevealProgress `protobuf:"bytes,2,opt,name=reveal_progress,json=revealProgress,proto3,oneof"`
}

func (*ImposterServerMessage_RoleAssignment) isImposterServerMessage_Body() {}

func (*ImposterServerMessage_RevealProgress) isImposterServerMessage_Body() {}

// Sent privately to each player at the start of a round. For the imposter,
// `word` and `category` are empty.
type RoleAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsImposter    bool                   `protobuf:"varint,1,opt,name=is_imposter,json=isImposter,proto3" json:"is_imposter,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignment) Reset() {
	*x = RoleAssignment{}
	mi := &file_imposter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignment) ProtoMessage() {}

func (x *RoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_imposter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignment.ProtoReflect.Descriptor instead.
func (*RoleAssignment) Descriptor() ([]byte, []int) {
	return file_imposter_proto_rawDescGZIP(), []int{1}
}

func (x *RoleAssignment) GetIsImposter() bool {
	if x != nil {
		return x.IsImposter
	}
	return false
}

func (x *RoleAssignment) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *RoleAssignment) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Broadcast as players confirm they have seen their role, so every client can
// show "3 / 5 ready".
type RevealProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadyPlayerIds []string               `protobuf:"bytes,1,rep,name=ready_player_ids,json=readyPlayerIds,proto3" json:"ready_player_ids,omitempty"`
	Total          int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevealProgress) Reset() {
	*x = RevealProgress{}
	mi := &file_imposter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealProgress) ProtoMessage() {}

func (x *RevealProgress) ProtoReflect() protoreflect.Message {
	mi := &file_imposter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealProgress.ProtoReflect.Descriptor instead.
func (*RevealProgress) Descriptor() ([]byte, []int) {
	return file_imposter_proto_rawDescGZIP(), []int{2}
}

func (x *RevealProgress) GetReadyPlayerIds() []string {
	if x != nil {
		return x.ReadyPlayerIds
	}
	return nil
}

func (x *RevealProgress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ImposterClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ImposterClientMessage_MarkReady
	Body          isImposterClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImposterClientMessage) Reset() {
	*x = ImposterClientMessage{}
	mi := &file_imposter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImposterClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImposterClientMessage) ProtoMessage() {}

func (x *ImposterClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_imposter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImposterClientMessage.ProtoReflect.Descriptor instead.
func (*ImposterClientMessage) Descriptor() ([]byte, []int) {
	return file_imposter_proto_rawDescGZIP(), []int{3}
}

func (x *ImposterClientMessage) GetBody() isImposterClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ImposterClientMessage) GetMarkReady() *MarkReady {
	if x != nil {
		if x, ok := x.Body.(*ImposterClientMessage_MarkReady); ok {
			return x.MarkReady
		}
	}
	return nil
}

type isImposterClientMessage_Body interface {
	isImposterClientMessage_Body()
}

type ImposterClientMessage_MarkReady struct {
	MarkReady *MarkReady `protobuf:"bytes,1,opt,name=mark_ready,json=markReady,proto3,oneof"`
}

func (*ImposterClientMessage_MarkReady) isImposterClientMessage_Body() {}

// "I have seen my role." When everyone has sent this, the round advances.
type MarkReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReady) Reset() {
	*x = MarkReady{}
	mi := &file_imposter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReady) ProtoMessage() {}

func (x *MarkReady) ProtoReflect() protoreflect.Message {
	mi := &file_imposter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReady.ProtoReflect.Descriptor instead.
func (*MarkReady) Descriptor() ([]byte, []int) {
	return file_imposter_proto_rawDescGZIP(), []int{4}
}

var File_imposter_proto protoreflect.FileDescriptor

const file_imposter_proto_rawDesc = "" +
	"\n" +
	"\x0eimposter.proto\x12\vimposter.v1\"\xaf\x01\n" +
	"\x15ImposterServerMessage\x12F\n" +
	"\x0frole_assignment\x18\x01 \x01(\v2\x1b.imposter.v1.RoleAssignmentH\x00R\x0eroleAssignment\x12F\n" +
	"\x0freveal_progress\x18\x02 \x01(\v2\x1b.imposter.v1.RevealProgressH\x00R\x0erevealProgressB\x06\n" +
	"\x04body\"a\n" +
	"\x0eRoleAssignment\x12\x1f\n" +
	"\vis_imposter\x18\x01 \x01(\bR\n" +
	"isImposter\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"P\n" +
	"\x0eRevealProgress\x12(\n" +
	"\x10ready_player_ids\x18\x01 \x03(\tR\x0ereadyPlayerIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"X\n" +
	"\x15ImposterClientMessage\x127\n" +
	"\n" +
	"mark_ready\x18\x01 \x01(\v2\x16.imposter.v1.MarkReadyH\x00R\tmarkReadyB\x06\n" +
	"\x04body\"\v\n" +
	"\tMarkReadyBGZEgithub.com/mintthiha/party-games/server/internal/games/imposter/pb;pbb\x06proto3"

var (
	file_imposter_proto_rawDescOnce sync.Once
	file_imposter_proto_rawDescData []byte
)

func file_imposter_proto_rawDescGZIP() []byte {
	file_imposter_proto_rawDescOnce.Do(func() {
		file_imposter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imposter_proto_rawDesc), len(file_imposter_proto_rawDesc)))
	})
	return file_imposter_proto_rawDescData
}

var file_imposter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_imposter_proto_goTypes = []any{
	(*ImposterServerMessage)(nil), // 0: imposter.v1.ImposterServerMessage
	(*RoleAssignment)(nil),        // 1: imposter.v1.RoleAssignment
	(*RevealProgress)(nil),        // 2: imposter.v1.RevealProgress
	(*ImposterClientMessage)(nil), // 3: imposter.v1.ImposterClientMessage
	(*MarkReady)(nil),             // 4: imposter.v1.MarkReady
}
var file_imposter_proto_depIdxs = []int32{
	1, // 0: imposter.v1.ImposterServerMessage.role_assignment:type_name -> imposter.v1.RoleAssignment
	2, // 1: imposter.v1.ImposterServerMessage.reveal_progress:type_name -> imposter.v1.RevealProgress
	4, // 2: imposter.v1.ImposterClientMessage.mark_ready:type_name -> imposter.v1.MarkReady
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_imposter_proto_init() }
func file_imposter_proto_init() {
	if File_imposter_proto != nil {
		return
	}
	file_imposter_proto_msgTypes[0].OneofWrappers = []any{
		(*ImposterServerMessage_RoleAssignment)(nil),
		(*ImposterServerMessage_RevealProgress)(nil),
	}
	file_imposter_proto_msgTypes[3].OneofWrappers = []any{
		(*ImposterClientMessage_MarkReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imposter_proto_rawDesc), len(file_imposter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imposter_proto_goTypes,
		DependencyIndexes: file_imposter_proto_depIdxs,
		MessageInfos:      file_imposter_proto_msgTypes,
	}.Build()
	File_imposter_proto = out.File
	file_imposter_proto_goTypes = nil
	file_imposter_proto_depIdxs = nil
}
