// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A connected player in a room. `id` is assigned by the server and is unique
// within a room for the lifetime of that connection.
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Every message a client sends is a ClientMessage with exactly one payload set.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_CreateRoom
	//	*ClientMessage_JoinRoom
	//	*ClientMessage_LeaveRoom
	//	*ClientMessage_Echo
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetCreateRoom() *CreateRoom {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

func (x *ClientMessage) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *ClientMessage) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *ClientMessage) GetEcho() *Echo {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_CreateRoom struct {
	CreateRoom *CreateRoom `protobuf:"bytes,1,opt,name=create_room,json=createRoom,proto3,oneof"`
}

type ClientMessage_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,2,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type ClientMessage_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,3,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type ClientMessage_Echo struct {
	Echo *Echo `protobuf:"bytes,4,opt,name=echo,proto3,oneof"`
}

func (*ClientMessage_CreateRoom) isClientMessage_Payload() {}

func (*ClientMessage_JoinRoom) isClientMessage_Payload() {}

func (*ClientMessage_LeaveRoom) isClientMessage_Payload() {}

func (*ClientMessage_Echo) isClientMessage_Payload() {}

// Ask the server to mint a new room. The server picks the room code and
// replies with RoomJoined.
type CreateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoom) Reset() {
	*x = CreateRoom{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom) ProtoMessage() {}

func (x *CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom.ProtoReflect.Descriptor instead.
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoom) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Join an existing room by code. Replies with RoomJoined, or ErrorInfo if the
// room does not exist.
type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoom) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *JoinRoom) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Leave the current room. The connection stays open; the client may create or
// join another room afterwards.
type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

// Round-trip probe. The server echoes `text` back to the whole room as
// EchoResult. Exists purely to prove the pipe works end to end.
type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *Echo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Every message the server sends is a ServerMessage with exactly one payload set.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RoomJoined
	//	*ServerMessage_PlayerJoined
	//	*ServerMessage_PlayerLeft
	//	*ServerMessage_EchoResult
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRoomJoined() *RoomJoined {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RoomJoined); ok {
			return x.RoomJoined
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *ServerMessage) GetEchoResult() *EchoResult {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_EchoResult); ok {
			return x.EchoResult
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorInfo {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RoomJoined struct {
	RoomJoined *RoomJoined `protobuf:"bytes,1,opt,name=room_joined,json=roomJoined,proto3,oneof"`
}

type ServerMessage_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,2,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type ServerMessage_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,3,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type ServerMessage_EchoResult struct {
	EchoResult *EchoResult `protobuf:"bytes,4,opt,name=echo_result,json=echoResult,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorInfo `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_RoomJoined) isServerMessage_Payload() {}

func (*ServerMessage_PlayerJoined) isServerMessage_Payload() {}

func (*ServerMessage_PlayerLeft) isServerMessage_Payload() {}

func (*ServerMessage_EchoResult) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

// Sent only to the player who just joined (via CreateRoom or JoinRoom):
// their own identity plus the full current roster, themselves included.
type RoomJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	SelfPlayerId  string                 `protobuf:"bytes,2,opt,name=self_player_id,json=selfPlayerId,proto3" json:"self_player_id,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoined) Reset() {
	*x = RoomJoined{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoined) ProtoMessage() {}

func (x *RoomJoined) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoined.ProtoReflect.Descriptor instead.
func (*RoomJoined) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *RoomJoined) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomJoined) GetSelfPlayerId() string {
	if x != nil {
		return x.SelfPlayerId
	}
	return ""
}

func (x *RoomJoined) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// Broadcast to the players already in a room when someone new joins.
type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerJoined) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

// Broadcast when a player leaves explicitly or their connection is reaped.
type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerLeft) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// Broadcast to the whole room in response to an Echo.
type EchoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	FromPlayerId  string                 `protobuf:"bytes,2,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResult) Reset() {
	*x = EchoResult{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResult) ProtoMessage() {}

func (x *EchoResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResult.ProtoReflect.Descriptor instead.
func (*EchoResult) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *EchoResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoResult) GetFromPlayerId() string {
	if x != nil {
		return x.FromPlayerId
	}
	return ""
}

// A problem with the client's last message. Not fatal to the connection.
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, machine-readable: "room_not_found", "not_in_room", "bad_message".
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable detail for logs and debugging. Not localized.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\rpartygames.v1\";\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\xf6\x01\n" +
	"\rClientMessage\x12<\n" +
	"\vcreate_room\x18\x01 \x01(\v2\x19.partygames.v1.CreateRoomH\x00R\n" +
	"createRoom\x126\n" +
	"\tjoin_room\x18\x02 \x01(\v2\x17.partygames.v1.JoinRoomH\x00R\bjoinRoom\x129\n" +
	"\n" +
	"leave_room\x18\x03 \x01(\v2\x18.partygames.v1.LeaveRoomH\x00R\tleaveRoom\x12)\n" +
	"\x04echo\x18\x04 \x01(\v2\x13.partygames.v1.EchoH\x00R\x04echoB\t\n" +
	"\apayload\"/\n" +
	"\n" +
	"CreateRoom\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"J\n" +
	"\bJoinRoom\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\v\n" +
	"\tLeaveRoom\"\x1a\n" +
	"\x04Echo\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xca\x02\n" +
	"\rServerMessage\x12<\n" +
	"\vroom_joined\x18\x01 \x01(\v2\x19.partygames.v1.RoomJoinedH\x00R\n" +
	"roomJoined\x12B\n" +
	"\rplayer_joined\x18\x02 \x01(\v2\x1b.partygames.v1.PlayerJoinedH\x00R\fplayerJoined\x12<\n" +
	"\vplayer_left\x18\x03 \x01(\v2\x19.partygames.v1.PlayerLeftH\x00R\n" +
	"playerLeft\x12<\n" +
	"\vecho_result\x18\x04 \x01(\v2\x19.partygames.v1.EchoResultH\x00R\n" +
	"echoResult\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x18.partygames.v1.ErrorInfoH\x00R\x05errorB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\n" +
	"RoomJoined\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12$\n" +
	"\x0eself_player_id\x18\x02 \x01(\tR\fselfPlayerId\x12/\n" +
	"\aplayers\x18\x03 \x03(\v2\x15.partygames.v1.PlayerR\aplayers\"=\n" +
	"\fPlayerJoined\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.partygames.v1.PlayerR\x06player\")\n" +
	"\n" +
	"PlayerLeft\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"F\n" +
	"\n" +
	"EchoResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12$\n" +
	"\x0efrom_player_id\x18\x02 \x01(\tR\ffromPlayerId\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBDZBgithub.com/mintthiha/party-games/server/internal/protocol;protocolb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protocol_proto_goTypes = []any{
	(*Player)(nil),        // 0: partygames.v1.Player
	(*ClientMessage)(nil), // 1: partygames.v1.ClientMessage
	(*CreateRoom)(nil),    // 2: partygames.v1.CreateRoom
	(*JoinRoom)(nil),      // 3: partygames.v1.JoinRoom
	(*LeaveRoom)(nil),     // 4: partygames.v1.LeaveRoom
	(*Echo)(nil),          // 5: partygames.v1.Echo
	(*ServerMessage)(nil), // 6: partygames.v1.ServerMessage
	(*RoomJoined)(nil),    // 7: partygames.v1.RoomJoined
	(*PlayerJoined)(nil),  // 8: partygames.v1.PlayerJoined
	(*PlayerLeft)(nil),    // 9: partygames.v1.PlayerLeft
	(*EchoResult)(nil),    // 10: partygames.v1.EchoResult
	(*ErrorInfo)(nil),     // 11: partygames.v1.ErrorInfo
}
var file_protocol_proto_depIdxs = []int32{
	2,  // 0: partygames.v1.ClientMessage.create_room:type_name -> partygames.v1.CreateRoom
	3,  // 1: partygames.v1.ClientMessage.join_room:type_name -> partygames.v1.JoinRoom
	4,  // 2: partygames.v1.ClientMessage.leave_room:type_name -> partygames.v1.LeaveRoom
	5,  // 3: partygames.v1.ClientMessage.echo:type_name -> partygames.v1.Echo
	7,  // 4: partygames.v1.ServerMessage.room_joined:type_name -> partygames.v1.RoomJoined
	8,  // 5: partygames.v1.ServerMessage.player_joined:type_name -> partygames.v1.PlayerJoined
	9,  // 6: partygames.v1.ServerMessage.player_left:type_name -> partygames.v1.PlayerLeft
	10, // 7: partygames.v1.ServerMessage.echo_result:type_name -> partygames.v1.EchoResult
	11, // 8: partygames.v1.ServerMessage.error:type_name -> partygames.v1.ErrorInfo
	0,  // 9: partygames.v1.RoomJoined.players:type_name -> partygames.v1.Player
	0,  // 10: partygames.v1.PlayerJoined.player:type_name -> partygames.v1.Player
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMessage_CreateRoom)(nil),
		(*ClientMessage_JoinRoom)(nil),
		(*ClientMessage_LeaveRoom)(nil),
		(*ClientMessage_Echo)(nil),
	}
	file_protocol_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_RoomJoined)(nil),
		(*ServerMessage_PlayerJoined)(nil),
		(*ServerMessage_PlayerLeft)(nil),
		(*ServerMessage_EchoResult)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
